# Game Configuration for Super Mario Bros
# Memory addresses, actions, and game-specific settings

game:
  # ROM and Emulator Settings
  rom_path: "roms/Super Mario Bros (World).nes"
  emulator: "fceux"
  target_world: 1                 # World to train on
  target_level: 1                 # Level to train on
  
  # Level Specifications
  level_specs:
    world_1_1:
      length: 3168                # Level length in pixels
      time_limit: 400             # Time limit in seconds
      completion_x: 3168          # X position for completion
      
  # Memory Address Mappings
  memory_addresses:
    # Mario Position and Movement
    mario_x_world_low: 0x0086     # Mario X position (world, low byte)
    mario_x_world_high: 0x03AD    # Mario X position (world, high byte)
    mario_y_world: 0x03B8         # Mario Y position (world)
    mario_x_screen: 0x006D        # Mario X position (screen)
    mario_y_screen: 0x00CE        # Mario Y position (screen)
    mario_x_velocity: 0x0057      # Mario X velocity
    mario_y_velocity: 0x009F      # Mario Y velocity
    mario_direction: 0x0045       # Mario facing direction
    mario_on_ground: 0x001D       # Mario on ground flag
    
    # Mario State
    power_state: 0x0756           # Mario power state (0=small, 1=big, 2=fire)
    lives: 0x075A                 # Lives remaining
    invincibility_timer: 0x079E   # Invincibility timer
    star_timer: 0x0770            # Star power timer
    animation_state: 0x0079       # Mario animation state
    crouching: 0x001E             # Mario crouching flag
    
    # Score and Collectibles
    score_100k: 0x07DD            # Score (100,000s digit)
    score_10k: 0x07DE             # Score (10,000s digit)
    score_1k: 0x07DF              # Score (1,000s digit)
    score_100: 0x07E0             # Score (100s digit)
    score_10: 0x07E1              # Score (10s digit)
    score_1: 0x07E2               # Score (1s digit)
    coins_10: 0x075E              # Coins (tens digit)
    coins_1: 0x075D               # Coins (ones digit)
    
    # Level and Time
    world_number: 0x075F          # Current world
    level_number: 0x0760          # Current level
    timer_100: 0x071A             # Timer (hundreds digit)
    timer_10: 0x071B              # Timer (tens digit)
    timer_1: 0x071C               # Timer (ones digit)
    
    # Camera and Screen
    screen_x_low: 0x0086          # Screen X position (low byte)
    screen_x_high: 0x03AD         # Screen X position (high byte)
    screen_y: 0x00B5              # Screen Y position
    vertical_scroll: 0x0725       # Vertical scroll
    
    # Enemies (8 slots)
    enemy_x_screen: [0x0087, 0x0088, 0x0089, 0x008A, 0x008B, 0x008C, 0x008D, 0x008E]
    enemy_y_screen: [0x00CF, 0x00D0, 0x00D1, 0x00D2, 0x00D3, 0x00D4, 0x00D5, 0x00D6]
    enemy_type: [0x0014, 0x0015, 0x0016, 0x0017, 0x0018, 0x0019, 0x001A, 0x001B]
    enemy_state: [0x001C, 0x001D, 0x001E, 0x001F, 0x0020, 0x0021, 0x0022, 0x0023]
    
    # Game State
    game_engine_state: 0x0770     # Game engine state
    player_state: 0x001D          # Player state
    game_mode: 0x0E               # Game mode
    level_complete_flag: 0x0772   # Level completion flag
    
    # Controller Input
    controller_1_input: 0x00F7    # Controller 1 current input
    controller_1_previous: 0x00F6 # Controller 1 previous input

  # Action Space Definition
  actions:
    0:
      name: "no_action"
      description: "No input"
      buttons: {}
      
    1:
      name: "right"
      description: "Move right"
      buttons: {right: true}
      
    2:
      name: "left" 
      description: "Move left"
      buttons: {left: true}
      
    3:
      name: "jump"
      description: "Jump"
      buttons: {A: true}
      
    4:
      name: "right_jump"
      description: "Move right and jump"
      buttons: {right: true, A: true}
      
    5:
      name: "left_jump"
      description: "Move left and jump"
      buttons: {left: true, A: true}
      
    6:
      name: "run"
      description: "Run/Fire"
      buttons: {B: true}
      
    7:
      name: "right_run"
      description: "Move right and run"
      buttons: {right: true, B: true}
      
    8:
      name: "left_run"
      description: "Move left and run"
      buttons: {left: true, B: true}
      
    9:
      name: "right_jump_run"
      description: "Forward jumping (right + jump + run)"
      buttons: {right: true, A: true, B: true}
      
    10:
      name: "left_jump_run"
      description: "Left jump with run"
      buttons: {left: true, A: true, B: true}
      
    11:
      name: "crouch"
      description: "Crouch/Down"
      buttons: {down: true}

# Reward System Configuration
rewards:
  # Primary Rewards (Level Progress)
  primary:
    forward_movement_multiplier: 1.0      # Reward per pixel forward
    milestone_multiplier: 10.0            # Bonus for new max distance
    completion_reward: 5000               # Level completion reward
    time_bonus_multiplier: 2.0            # Time remaining bonus
    progress_bonuses: [100, 200, 300, 500] # Milestone bonuses
    
  # Secondary Rewards (Survival/Scoring)
  secondary:
    powerup_rewards: [0, 200, 400]        # Small, big, fire Mario
    enemy_kill_reward: 100                # Base enemy elimination reward
    coin_reward: 50                       # Coin collection reward
    score_multiplier: 0.01                # Score increase multiplier
    
  # Penalties
  penalties:
    death_penalty: -1000                  # Death penalty
    backward_movement_multiplier: -0.5    # Backward movement penalty
    stuck_penalty_per_frame: -1.0         # Stuck behavior penalty
    stuck_threshold_frames: 60            # Frames before stuck penalty
    
  # Reward Shaping
  shaping:
    curriculum_enabled: true              # Enable curriculum learning
    adaptive_scaling: true                # Adaptive reward scaling
    reward_clipping: [-2000, 2000]        # Reward clipping range